name: CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
<<<<<<< HEAD
    uses: voikyrioh/infra-as-code/.github/workflows/deploy-app.yml@main
=======
    uses: voikyrioh/infra-as-code/.github/workflows/deploy-app.yml@main
>>>>>>> 04a43c7 (fix: correct infra repo name in reusable workflow reference)
    with:
      app_name: dofus-retro-db
      image_name: dofus-retro-db
    secrets:
      VPS_HOST: ${{ secrets.SSH_HOST }}
      VPS_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      VPS_SSH_PORT: ${{ secrets.SSH_PORT }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
      VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
      VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
